### ISSUE TITLE
Connection error: Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by konstzhukov** [sj26/homebridge-intesisbox#1]
Hello! Periodically I got the following errors in Homebridge:
0|homebrid | [7/22/2020, 19:34:01] [Air Conditioner] Connection error: Error: This socket has been ended by the other party
0|homebrid |     at Socket.writeAfterFIN [as write] (net.js:454:14)
0|homebrid |     at Intesisbox.send (/usr/local/lib/node_modules/homebridge-intesisbox/index.js:317:17)
0|homebrid |     at Intesisbox.sendSET (/usr/local/lib/node_modules/homebridge-intesisbox/index.js:345:10)
0|homebrid |     at Intesisbox.<anonymous> (/usr/local/lib/node_modules/homebridge-intesisbox/index.js:104:16)
0|homebrid |     at TargetHeatingCoolingState.emit (events.js:315:20)
0|homebrid |     at TargetHeatingCoolingState.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
0|homebrid |     at TargetHeatingCoolingState.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:625:12)
0|homebrid |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
0|homebrid |     at Array.forEach (<anonymous>)
0|homebrid |     at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10) {
0|homebrid |   code: 'EPIPE'
0|homebrid | }

I am using the updated version of index.js

Could you please help to identify the root cause?

Best regards,
Konstantin.

**Comment by sj26** [comment]
Hiya! Sounds like your intesisbox is closing the connection after a timeout, or something. Or you might have transient networking issues.

The code is designed to recover from these errors, it’s just being verbose. 😊
